<script>
import {
  // navigation / chevrons / arrows
  Plus, ChevronDown, ChevronLeft, ChevronRight, ArrowLeft, ArrowUpCircle,
  // files / folders
  FilePlus, Files, Folder, FileText, ClipboardList, Copy,
  // commerce
  ShoppingCart, ShoppingBasket, ShoppingBag, Store, CreditCard, Wallet,
  Banknote, DollarSign, Receipt, ReceiptText, Tag, Ticket, Barcode,
  // people
  User, UserPlus, UserMinus, Users, IdCard, BriefcaseBusiness, ShieldCheck,
  // tools / settings
  Settings, Wrench, Key, Lock, Shield, Bug,
  // analytics / charts
  BarChart3, PieChart, TrendingUp, TrendingDown, Activity, MonitorUp, Minus,
  // data / cloud
  Database, DatabaseBackup, DatabaseZap, Cloud, Archive, Download,
  // time
  Clock, AlarmClock, Timer, Hourglass, CalendarDays, Calendar,
  // misc
  Bell, BellRing, Book, Bookmark, Library, LibraryBig, Lightbulb,
  Heart, HeartPulse, Trophy, Quote, MessageSquare, MapPin, Mail,
  Package, Pencil, Check, CheckCheck, Camera, Atom, Warehouse, AppWindow,
  Calculator, Building, Star, X,
  CloudMoon, Maximize, Globe, Sun,
  Eye, FileSpreadsheet, Filter, Info, Power,
  Home, StickyNote, EyeOff,
  BarChart2, Pen, RefreshCw,
  Search, Flag, List,
  Columns3, PackageOpen, Loader, Pause, Repeat, HelpCircle,
  ArrowRight, MoreVertical,
  GripVertical, Paintbrush, Printer,
  Brain, Table, Sparkles, Play, Zap, LayoutDashboard, AlertCircle, AlertTriangle,
  CloudSun, File, FileUp, Upload,
  Inbox,
  Code, FilePen, Medal, Image as LucideImage, QrCode, Trash2, Ruler, Settings2, Columns2, Rows2,
  Monitor, CheckCircle, Circle, FileDown, Smartphone,
  ArrowRightLeft, XCircle, CloudCheck, MousePointerClick, MousePointer, Menu, KeyRound, RefreshCcw, Square,
  Coins, CornerUpLeft, CornerUpRight, Undo,
  Send, Puzzle, Server, FileArchive,
  ArrowUp, Scale, Landmark, Music, Phone,
  Volume2, VolumeX
} from 'lucide-vue';

const REGISTRY = {
  // navigation
  'plus': Plus,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left': ArrowLeft,
  'arrow-up-circle': ArrowUpCircle,
  // files
  'file-plus': FilePlus,
  'files': Files,
  'folder': Folder,
  'file-text': FileText,
  'clipboard-list': ClipboardList,
  'copy': Copy,
  // commerce
  'shopping-cart': ShoppingCart,
  'shopping-basket': ShoppingBasket,
  'shopping-bag': ShoppingBag,
  'store': Store,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'banknote': Banknote,
  'dollar-sign': DollarSign,
  'receipt': Receipt,
  'receipt-text': ReceiptText,
  'tag': Tag,
  'ticket': Ticket,
  'barcode': Barcode,
  // people
  'user': User,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'users': Users,
  'id-card': IdCard,
  'briefcase-business': BriefcaseBusiness,
  'shield-check': ShieldCheck,
  // tools
  'settings': Settings,
  'wrench': Wrench,
  'key': Key,
  'lock': Lock,
  'shield': Shield,
  'bug': Bug,
  // analytics
  'bar-chart': BarChart3,
  'bar-chart-3': BarChart3,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'minus': Minus,
  'activity': Activity,
  'monitor-up': MonitorUp,
  // data / cloud
  'database': Database,
  'database-backup': DatabaseBackup,
  'database-zap': DatabaseZap,
  'cloud': Cloud,
  'archive': Archive,
  'download': Download,
  // time
  'clock': Clock,
  'alarm-clock': AlarmClock,
  'timer': Timer,
  'hourglass': Hourglass,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  // misc
  'bell': Bell,
  'bell-ring': BellRing,
  'book': Book,
  'bookmark': Bookmark,
  'library': Library,
  'library-big': LibraryBig,
  'lightbulb': Lightbulb,
  'heart': Heart,
  'heart-pulse': HeartPulse,
  'trophy': Trophy,
  'quote': Quote,
  'message-square': MessageSquare,
  'map-pin': MapPin,
  'mail': Mail,
  'package': Package,
  'pencil': Pencil,
  'check': Check,
  'check-check': CheckCheck,
  'camera': Camera,
  'atom': Atom,
  'warehouse': Warehouse,
  'app-window': AppWindow,
  'calculator': Calculator,
  'building': Building,
  'star': Star,
  'x': X,
  'cloud-moon': CloudMoon,
  'maximize': Maximize,
  'globe': Globe,
  'sun': Sun,
  'eye': Eye,
  'file-spreadsheet': FileSpreadsheet,
  'filter': Filter,
  'info': Info,
  'power': Power,
  'home': Home,
  'sticky-note': StickyNote,
  'eye-off': EyeOff,
  'bar-chart-2': BarChart2,
  'pen': Pen,
  'refresh-cw': RefreshCw,
  'search': Search,
  'flag': Flag,
  'list': List,
  'columns-3': Columns3,
  'package-open': PackageOpen,
  'loader': Loader,
  'pause': Pause,
  'repeat': Repeat,
  'help-circle': HelpCircle,
  'arrow-right': ArrowRight,
  'more-vertical': MoreVertical,
  'grip-vertical': GripVertical,
  'paintbrush': Paintbrush,
  'printer': Printer,
  'brain': Brain,
  'table': Table,
  'sparkles': Sparkles,
  'play': Play,
  'zap': Zap,
  'layout-dashboard': LayoutDashboard,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'cloud-sun': CloudSun,
  'file': File,
  'file-up': FileUp,
  'upload': Upload,
  'inbox': Inbox,
  'code': Code,
  'file-pen': FilePen,
  'medal': Medal,
  'image': LucideImage,
  'qr-code': QrCode,
  'trash-2': Trash2,
  'ruler': Ruler,
  'settings-2': Settings2,
  'columns-2': Columns2,
  'rows-2': Rows2,
  'monitor': Monitor,
  'check-circle': CheckCircle,
  'circle': Circle,
  'file-down': FileDown,
  'smartphone': Smartphone,
  'arrow-right-left': ArrowRightLeft,
  'x-circle': XCircle,
  'cloud-check': CloudCheck,
  'mouse-pointer-click': MousePointerClick,
  'mouse-pointer': MousePointer,
  'menu': Menu,
  'key-round': KeyRound,
  'refresh-ccw': RefreshCcw,
  'square': Square,
  'coins': Coins,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  'undo': Undo,
  'send': Send,
  'puzzle': Puzzle,
  'server': Server,
  'file-archive': FileArchive,
  'arrow-up': ArrowUp,
  'scale': Scale,
  'landmark': Landmark,
  'music': Music,
  'phone': Phone,
  'volume-2': Volume2,
  'volume-x': VolumeX,
};

export default {
  name: 'LucideIcon',
  functional: true,
  props: {
    name: { type: String, required: true },
    size: { type: [Number, String], default: 18 },
    strokeWidth: { type: [Number, String], default: 2 },
  },
  render(h, ctx) {
    const Icon = REGISTRY[ctx.props.name];
    if (!Icon) {
      if (typeof console !== 'undefined' && console.warn) {
        console.warn('[LucideIcon] missing icon:', ctx.props.name);
      }
      return h('span', { class: ['lucide-icon', 'lucide-missing'], attrs: { 'data-name': ctx.props.name } });
    }
    return h(Icon, {
      class: ['lucide-icon', ctx.data.class, ctx.data.staticClass].filter(Boolean),
      style: [ctx.data.style, ctx.data.staticStyle].filter(Boolean),
      attrs: ctx.data.attrs,
      props: { size: ctx.props.size, strokeWidth: ctx.props.strokeWidth },
      on: ctx.listeners,
    });
  },
};
</script>
